import type { Metadata } from "next";
import { Geist, Geist_Mono as GeistMono, Josefin_Sans as JosefinSans } from "next/font/google";
import "./globals.css";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = GeistMono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const josefinSans = JosefinSans({
  variable: "--font-josefin-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    authors: [{name: "Sanjigen dev team"}],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${josefinSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
